mkdir "1 de mayo x cl 40 sur"
mkdir "1 de mayo x cl 43 sur"
mkdir "1demayoXcaracas"
mkdir "kr 68 x cl 44 sur"
mkdir "kr 135 x centenario"
mkdir "kr 9 x caracas (molinos)"
mkdir "caracas x cl 6"
mkdir "kr 68 x cl 3"
mkdir "cali x cl 72"
mkdir "kr 27 x 1 de mayo"
mkdir "kr 128 x centenario"
mkdir "kr 70 x cl 72"